# coding: utf-8

"""
    Mobi

    Mobi REST API Documentation  # noqa: E501

    OpenAPI spec version: 1.22.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.policies_api import PoliciesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPoliciesApi(unittest.TestCase):
    """PoliciesApi unit test stubs"""

    def setUp(self):
        self.api = PoliciesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_policy(self):
        """Test case for create_policy

        Creates a new security policy using the provided JSON body  # noqa: E501
        """
        pass

    def test_get_policies(self):
        """Test case for get_policies

        Retrieves security policies matching the provided filters  # noqa: E501
        """
        pass

    def test_retrieve_policy(self):
        """Test case for retrieve_policy

        Retrieves a specific security policy by its ID  # noqa: E501
        """
        pass

    def test_update_policy(self):
        """Test case for update_policy

        Updates an existing security policy using the provided JSON body  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
