# coding: utf-8

"""
    Mobi

    Mobi REST API Documentation  # noqa: E501

    OpenAPI spec version: 1.22.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.document_name_mappreview_body import DocumentNameMappreviewBody  # noqa: E501
from swagger_client.rest import ApiException


class TestDocumentNameMappreviewBody(unittest.TestCase):
    """DocumentNameMappreviewBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocumentNameMappreviewBody(self):
        """Test DocumentNameMappreviewBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.document_name_mappreview_body.DocumentNameMappreviewBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
