# coding: utf-8

"""
    Mobi

    Mobi REST API Documentation  # noqa: E501

    OpenAPI spec version: 1.22.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.users_api import UsersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_user_group(self):
        """Test case for add_user_group

        Add a Mobi user to a group  # noqa: E501
        """
        pass

    def test_add_user_roles(self):
        """Test case for add_user_roles

        Add roles to a Mobi User  # noqa: E501
        """
        pass

    def test_change_password(self):
        """Test case for change_password

        Changes a Mobi User's password if it is the User making the request  # noqa: E501
        """
        pass

    def test_create_user(self):
        """Test case for create_user

        Create a Mobi User account  # noqa: E501
        """
        pass

    def test_delete_user(self):
        """Test case for delete_user

        Remove a Mobi user's account  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        Get a single Mobi User  # noqa: E501
        """
        pass

    def test_get_user_roles(self):
        """Test case for get_user_roles

        List roles of a Mobi User  # noqa: E501
        """
        pass

    def test_get_username(self):
        """Test case for get_username

        Retrieve a username based on the passed User IRI  # noqa: E501
        """
        pass

    def test_get_users(self):
        """Test case for get_users

        Get all Mobi Users  # noqa: E501
        """
        pass

    def test_list_user_groups(self):
        """Test case for list_user_groups

        List groups of a Mobi User  # noqa: E501
        """
        pass

    def test_remove_user_group(self):
        """Test case for remove_user_group

        Remove a Mobi User from a group  # noqa: E501
        """
        pass

    def test_remove_user_role(self):
        """Test case for remove_user_role

        Remove role from a Mobi User  # noqa: E501
        """
        pass

    def test_reset_password(self):
        """Test case for reset_password

        Resets a Mobi User's password if User making request is the admin  # noqa: E501
        """
        pass

    def test_update_user(self):
        """Test case for update_user

        Update a Mobi user's information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
