# coding: utf-8

"""
    Mobi

    Mobi REST API Documentation  # noqa: E501

    OpenAPI spec version: 1.22.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.merge_requests_api import MergeRequestsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMergeRequestsApi(unittest.TestCase):
    """MergeRequestsApi unit test stubs"""

    def setUp(self):
        self.api = MergeRequestsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accept_merge_request(self):
        """Test case for accept_merge_request

        Accepts a MergeRequest by performing the merge and changing the type  # noqa: E501
        """
        pass

    def test_create_comment(self):
        """Test case for create_comment

        Creates a new Comment on the MergeRequest in the application with the provided information  # noqa: E501
        """
        pass

    def test_create_merge_requests(self):
        """Test case for create_merge_requests

        Creates a new MergeRequest in the application with the provided information  # noqa: E501
        """
        pass

    def test_delete_comment(self):
        """Test case for delete_comment

        Deletes a Comment that has the provided commentId  # noqa: E501
        """
        pass

    def test_delete_merge_request(self):
        """Test case for delete_merge_request

        Deletes a MergeRequest that has the provided requestId  # noqa: E501
        """
        pass

    def test_get_comment(self):
        """Test case for get_comment

        Retrieves a Comment from the application by its ID  # noqa: E501
        """
        pass

    def test_get_comments(self):
        """Test case for get_comments

        Retrieves all Comment threads on a MergeRequest sorted by issued date of the head of each comment chain  # noqa: E501
        """
        pass

    def test_get_merge_request(self):
        """Test case for get_merge_request

        Retrieves a MergeRequest from the application by its ID  # noqa: E501
        """
        pass

    def test_get_merge_requests(self):
        """Test case for get_merge_requests

        Retrieves all MergeRequests in the application  # noqa: E501
        """
        pass

    def test_update_comment(self):
        """Test case for update_comment

        Updates a Comment by its ID using the provided String  # noqa: E501
        """
        pass

    def test_update_merge_request(self):
        """Test case for update_merge_request

        Updates an existing MergeRequest that has the requestId with the provided JSONLD of newMergeRequest  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
