# coding: utf-8

"""
    Mobi

    Mobi REST API Documentation  # noqa: E501

    OpenAPI spec version: 1.22.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.translate_api import TranslateApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTranslateApi(unittest.TestCase):
    """TranslateApi unit test stubs"""

    def setUp(self):
        self.api = TranslateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_translate_document(self):
        """Test case for translate_document

        Accepts an input File of either csv, json, or xml and transforms it to an ontology and data file  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
