# coding: utf-8

"""
    Mobi

    Mobi REST API Documentation  # noqa: E501

    OpenAPI spec version: 1.22.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.provenance_data_api import ProvenanceDataApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProvenanceDataApi(unittest.TestCase):
    """ProvenanceDataApi unit test stubs"""

    def setUp(self):
        self.api = ProvenanceDataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_activities(self):
        """Test case for get_activities

        Retrieves a JSON object with a paginated list of provenance Activities and referenced Entities  # noqa: E501
        """
        pass

    def test_get_activity(self):
        """Test case for get_activity

        Retrieves a JSON object representing the passed in provenance Activity  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
