# coding: utf-8

"""
    Mobi

    Mobi REST API Documentation  # noqa: E501

    OpenAPI spec version: 1.22.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.record_id_inprogresscommit_body import RecordIdInprogresscommitBody  # noqa: E501
from swagger_client.rest import ApiException


class TestRecordIdInprogresscommitBody(unittest.TestCase):
    """RecordIdInprogresscommitBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecordIdInprogresscommitBody(self):
        """Test RecordIdInprogresscommitBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.record_id_inprogresscommit_body.RecordIdInprogresscommitBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
