# coding: utf-8

"""
    Mobi

    Mobi REST API Documentation  # noqa: E501

    OpenAPI spec version: 1.22.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.shapes_graphs_api import ShapesGraphsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestShapesGraphsApi(unittest.TestCase):
    """ShapesGraphsApi unit test stubs"""

    def setUp(self):
        self.api = ShapesGraphsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_shapes_graph(self):
        """Test case for delete_shapes_graph

        Deletes the SHACL Shapes Graph record with the associated record ID  # noqa: E501
        """
        pass

    def test_download_shapes_graph(self):
        """Test case for download_shapes_graph

        Streams the SHACL Shapes Graph associated with the requested record ID to an OutputStream  # noqa: E501
        """
        pass

    def test_get_entity1(self):
        """Test case for get_entity1

        Retrieves the triples for a specified entity  # noqa: E501
        """
        pass

    def test_get_shapes_graph_content(self):
        """Test case for get_shapes_graph_content

        Retrieves the triples for a specified entity  # noqa: E501
        """
        pass

    def test_get_shapes_graph_id(self):
        """Test case for get_shapes_graph_id

        Retrieves the Shapes Graph ID for the specified record, branch, and commit  # noqa: E501
        """
        pass

    def test_upload_file1(self):
        """Test case for upload_file1

        Uploads a shapes-graph file to the data store  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
