# coding: utf-8

"""
    Mobi

    Mobi REST API Documentation  # noqa: E501

    OpenAPI spec version: 1.22.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.record_id_distributions_body import RecordIdDistributionsBody  # noqa: E501
from swagger_client.rest import ApiException


class TestRecordIdDistributionsBody(unittest.TestCase):
    """RecordIdDistributionsBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecordIdDistributionsBody(self):
        """Test RecordIdDistributionsBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.record_id_distributions_body.RecordIdDistributionsBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
