# coding: utf-8

"""
    Mobi

    Mobi REST API Documentation  # noqa: E501

    OpenAPI spec version: 1.22.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.delimited_files_api import DelimitedFilesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDelimitedFilesApi(unittest.TestCase):
    """DelimitedFilesApi unit test stubs"""

    def setUp(self):
        self.api = DelimitedFilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_etl_file(self):
        """Test case for etl_file

        ETL an uploaded delimited document using an uploaded Mapping file and load data into a Dataset  # noqa: E501
        """
        pass

    def test_etl_file1(self):
        """Test case for etl_file1

        ETL an uploaded delimited document using an uploaded Mapping file and download the data  # noqa: E501
        """
        pass

    def test_etl_file_ontology(self):
        """Test case for etl_file_ontology

        ETL an uploaded delimited document using an uploaded Mapping file and commit it to an OntologyRecord  # noqa: E501
        """
        pass

    def test_etl_file_preview(self):
        """Test case for etl_file_preview

        ETL an uploaded delimited document using mapping JSON-LD  # noqa: E501
        """
        pass

    def test_get_rows(self):
        """Test case for get_rows

        Gather rows from an uploaded delimited document  # noqa: E501
        """
        pass

    def test_upload(self):
        """Test case for upload

        Upload delimited file sent as form data  # noqa: E501
        """
        pass

    def test_upload1(self):
        """Test case for upload1

        Replace an uploaded delimited file with another  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
