# coding: utf-8

"""
    Mobi

    Mobi REST API Documentation  # noqa: E501

    OpenAPI spec version: 1.22.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.settings_api import SettingsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSettingsApi(unittest.TestCase):
    """SettingsApi unit test stubs"""

    def setUp(self):
        self.api = SettingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_setting(self):
        """Test case for create_setting

        Creates a Setting and it's referenced entities from the provided body.  # noqa: E501
        """
        pass

    def test_delete_setting(self):
        """Test case for delete_setting

        Deletes a Setting who has the subjectId of settingId.  # noqa: E501
        """
        pass

    def test_delete_setting_by_type(self):
        """Test case for delete_setting_by_type

        Deletes the Setting whose type is the provided settingType  # noqa: E501
        """
        pass

    def test_get_all_settings(self):
        """Test case for get_all_settings

        Retrieves all Settings of the provided type.  # noqa: E501
        """
        pass

    def test_get_groups1(self):
        """Test case for get_groups1

        Retrieves all SettingGroups.  # noqa: E501
        """
        pass

    def test_get_setting(self):
        """Test case for get_setting

        Retrieves a Setting identified by the settingId.  # noqa: E501
        """
        pass

    def test_get_setting_by_type(self):
        """Test case for get_setting_by_type

        Retrieves the Setting whose type is the provided settingType  # noqa: E501
        """
        pass

    def test_get_setting_definitions(self):
        """Test case for get_setting_definitions

        Retrieves SettingGroup definitions associated with the provided groupId  # noqa: E501
        """
        pass

    def test_update_setting(self):
        """Test case for update_setting

        Updates a Setting it's referenced entities using the provided body.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
