# coding: utf-8

"""
    Mobi

    Mobi REST API Documentation  # noqa: E501

    OpenAPI spec version: 1.22.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.session_api import SessionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSessionApi(unittest.TestCase):
    """SessionApi unit test stubs"""

    def setUp(self):
        self.api = SessionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_current_user(self):
        """Test case for get_current_user

        Gets the current user token  # noqa: E501
        """
        pass

    def test_login(self):
        """Test case for login

        Logs in into Mobi creating a new token  # noqa: E501
        """
        pass

    def test_logout(self):
        """Test case for logout

        Logs out of Mobi by setting unauth token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
