# coding: utf-8

"""
    Mobi

    Mobi REST API Documentation  # noqa: E501

    OpenAPI spec version: 1.22.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.record_permissions_api import RecordPermissionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRecordPermissionsApi(unittest.TestCase):
    """RecordPermissionsApi unit test stubs"""

    def setUp(self):
        self.api = RecordPermissionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_retrieve_record_policy(self):
        """Test case for retrieve_record_policy

        Retrieves a specific record security policy by its ID  # noqa: E501
        """
        pass

    def test_update_record_policy(self):
        """Test case for update_record_policy

        Updates an existing record security policy using the provided JSON body  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
