# coding: utf-8

"""
    Mobi

    Mobi REST API Documentation  # noqa: E501

    OpenAPI spec version: 1.22.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.pep_api import PepApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPepApi(unittest.TestCase):
    """PepApi unit test stubs"""

    def setUp(self):
        self.api = PepApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_evaluate_request(self):
        """Test case for evaluate_request

        Converts user provided request into XACML and evaluates  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
