# coding: utf-8

"""
    Mobi

    Mobi REST API Documentation  # noqa: E501

    OpenAPI spec version: 1.22.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.ontologies_api import OntologiesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOntologiesApi(unittest.TestCase):
    """OntologiesApi unit test stubs"""

    def setUp(self):
        self.api = OntologiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_annotation_to_ontology(self):
        """Test case for add_annotation_to_ontology

        Adds a new annotation to the identified ontology  # noqa: E501
        """
        pass

    def test_add_class_to_ontology(self):
        """Test case for add_class_to_ontology

        Adds a new class to the identified ontology  # noqa: E501
        """
        pass

    def test_add_data_property_to_ontology(self):
        """Test case for add_data_property_to_ontology

        Adds a new data property to the identified ontology  # noqa: E501
        """
        pass

    def test_add_datatype_to_ontology(self):
        """Test case for add_datatype_to_ontology

        Adds a new datatype to the identified ontology  # noqa: E501
        """
        pass

    def test_add_individual_to_ontology(self):
        """Test case for add_individual_to_ontology

        Adds a new individual to the identified ontology  # noqa: E501
        """
        pass

    def test_add_object_property_to_ontology(self):
        """Test case for add_object_property_to_ontology

        Adds a new object property to the identified ontology  # noqa: E501
        """
        pass

    def test_delete_annotation_from_ontology(self):
        """Test case for delete_annotation_from_ontology

        Updates the specified ontology branch and commit with the data provided  # noqa: E501
        """
        pass

    def test_delete_class_from_ontology(self):
        """Test case for delete_class_from_ontology

        Deletes the identified class from the identified ontology  # noqa: E501
        """
        pass

    def test_delete_data_property_from_ontology(self):
        """Test case for delete_data_property_from_ontology

        Deletes the identified data property from the identified ontology  # noqa: E501
        """
        pass

    def test_delete_datatype_from_ontology(self):
        """Test case for delete_datatype_from_ontology

        Deletes the identified datatype from the identified ontology  # noqa: E501
        """
        pass

    def test_delete_individual_from_ontology(self):
        """Test case for delete_individual_from_ontology

        Deletes the identified individual from the identified ontology  # noqa: E501
        """
        pass

    def test_delete_object_property_from_ontology(self):
        """Test case for delete_object_property_from_ontology

        Deletes the identified object property from the identified ontology  # noqa: E501
        """
        pass

    def test_delete_ontology(self):
        """Test case for delete_ontology

        Deletes the OntologyRecord with the requested recordId  # noqa: E501
        """
        pass

    def test_delete_ontology_branch(self):
        """Test case for delete_ontology_branch

        Deletes the Branch with the requested BranchId from the OntologyRecord with the provided recordId  # noqa: E501
        """
        pass

    def test_get_annotations_in_imported_ontologies(self):
        """Test case for get_annotations_in_imported_ontologies

        Gets the annotations from the imported ontologies of the identified ontology  # noqa: E501
        """
        pass

    def test_get_annotations_in_ontology(self):
        """Test case for get_annotations_in_ontology

        Gets the annotations in the identified ontology  # noqa: E501
        """
        pass

    def test_get_classes_in_imported_ontologies(self):
        """Test case for get_classes_in_imported_ontologies

        Gets the classes from the imported ontologies of the identified ontology  # noqa: E501
        """
        pass

    def test_get_classes_in_ontology(self):
        """Test case for get_classes_in_ontology

        Gets the classes in the identified ontology  # noqa: E501
        """
        pass

    def test_get_classes_with_individuals(self):
        """Test case for get_classes_with_individuals

        Gets the classes with individuals in a hierarchical structure for the identified ontology  # noqa: E501
        """
        pass

    def test_get_concept_hierarchy(self):
        """Test case for get_concept_hierarchy

        Gets the concept hierarchies for the identified ontology  # noqa: E501
        """
        pass

    def test_get_concept_scheme_hierarchy(self):
        """Test case for get_concept_scheme_hierarchy

        Gets the concept hierarchies for the identified ontology  # noqa: E501
        """
        pass

    def test_get_data_properties_in_imported_ontologies(self):
        """Test case for get_data_properties_in_imported_ontologies

        Gets the data properties from the imported ontologies of the identified ontology  # noqa: E501
        """
        pass

    def test_get_data_properties_in_ontology(self):
        """Test case for get_data_properties_in_ontology

        Gets the data properties from the identified ontology  # noqa: E501
        """
        pass

    def test_get_datatypes_in_imported_ontologies(self):
        """Test case for get_datatypes_in_imported_ontologies

        Gets the datatypes from the imported ontologies of the identified ontology  # noqa: E501
        """
        pass

    def test_get_datatypes_in_ontology(self):
        """Test case for get_datatypes_in_ontology

        Gets the datatypes in the identified ontology  # noqa: E501
        """
        pass

    def test_get_entity(self):
        """Test case for get_entity

        Retrieves the triples for a specified entity including all of is transitively attached Blank Node  # noqa: E501
        """
        pass

    def test_get_entity_names(self):
        """Test case for get_entity_names

        Updates the specified ontology branch and commit with the data provided  # noqa: E501
        """
        pass

    def test_get_entity_usages(self):
        """Test case for get_entity_usages

        Gets the usages of the identified entity in the identified ontology  # noqa: E501
        """
        pass

    def test_get_failed_imports(self):
        """Test case for get_failed_imports

        Gets a list of ontology IRIs that were not imported  # noqa: E501
        """
        pass

    def test_get_imported_ontology_ir_is(self):
        """Test case for get_imported_ontology_ir_is

        Gets the imported ontology IRIs of the identified ontology  # noqa: E501
        """
        pass

    def test_get_imports_closure(self):
        """Test case for get_imports_closure

        Updates the specified ontology branch and commit with the data provided  # noqa: E501
        """
        pass

    def test_get_ir_is_in_imported_ontologies(self):
        """Test case for get_ir_is_in_imported_ontologies

        Gets the IRIs from the imported ontologies of the identified ontology  # noqa: E501
        """
        pass

    def test_get_ir_is_in_ontology(self):
        """Test case for get_ir_is_in_ontology

        Gets the IRIs in the identified ontology  # noqa: E501
        """
        pass

    def test_get_named_individuals_in_imported_ontologies(self):
        """Test case for get_named_individuals_in_imported_ontologies

        Gets the named individuals from the imported ontologies of the identified ontology  # noqa: E501
        """
        pass

    def test_get_named_individuals_in_ontology(self):
        """Test case for get_named_individuals_in_ontology

        Gets the individuals in the identified ontology  # noqa: E501
        """
        pass

    def test_get_object_properties_in_imported_ontologies(self):
        """Test case for get_object_properties_in_imported_ontologies

        Gets the object properties from the imported ontologies of the identified ontology  # noqa: E501
        """
        pass

    def test_get_object_properties_in_ontology(self):
        """Test case for get_object_properties_in_ontology

        Gets the object properties in the identified ontology  # noqa: E501
        """
        pass

    def test_get_ontology(self):
        """Test case for get_ontology

        Returns the ontology associated with the requested record ID in the requested format  # noqa: E501
        """
        pass

    def test_get_ontology_annotation_property_hierarchy(self):
        """Test case for get_ontology_annotation_property_hierarchy

        Gets the data property hierarchies for the identified ontology  # noqa: E501
        """
        pass

    def test_get_ontology_class_hierarchy(self):
        """Test case for get_ontology_class_hierarchy

        Gets the class hierarchies for the identified ontology  # noqa: E501
        """
        pass

    def test_get_ontology_data_property_hierarchy(self):
        """Test case for get_ontology_data_property_hierarchy

        Gets the data property hierarchies for the identified ontology  # noqa: E501
        """
        pass

    def test_get_ontology_object_property_hierarchy(self):
        """Test case for get_ontology_object_property_hierarchy

        Gets the object property hierarchies for the identified ontology  # noqa: E501
        """
        pass

    def test_get_ontology_stuff(self):
        """Test case for get_ontology_stuff

        Gets a JSON representation of all the OWL ontology related information about the ontology  # noqa: E501
        """
        pass

    def test_get_property_to_ranges(self):
        """Test case for get_property_to_ranges

        Gets a JSON representation of the properties Ranges  # noqa: E501
        """
        pass

    def test_get_search_results(self):
        """Test case for get_search_results

        Gets the search results from the identified ontology using the provided searchText  # noqa: E501
        """
        pass

    def test_get_vocabulary_stuff(self):
        """Test case for get_vocabulary_stuff

        Gets a JSON representation of all the SKOS vocabulary related information about the ontology  # noqa: E501
        """
        pass

    def test_post_url_encoded_download_query_ontology(self):
        """Test case for post_url_encoded_download_query_ontology

        Downloads the SPARQL query results of an ontology, and its import closures in the requested format  # noqa: E501
        """
        pass

    def test_query_ontology(self):
        """Test case for query_ontology

        Retrieves the SPARQL query results of an ontology, and its import closures in the requested format  # noqa: E501
        """
        pass

    def test_save_changes_to_ontology(self):
        """Test case for save_changes_to_ontology

        Updates the requester's InProgressCommit with the provided entity  # noqa: E501
        """
        pass

    def test_upload_changes_to_ontology(self):
        """Test case for upload_changes_to_ontology

        Updates the specified ontology branch and commit with the data provided  # noqa: E501
        """
        pass

    def test_upload_file(self):
        """Test case for upload_file

        Uploads an ontology file to the data store  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
