# coding: utf-8

"""
    Mobi

    Mobi REST API Documentation  # noqa: E501

    OpenAPI spec version: 1.22.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sparql_api import SparqlApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSparqlApi(unittest.TestCase):
    """SparqlApi unit test stubs"""

    def setUp(self):
        self.api = SparqlApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_limited_results(self):
        """Test case for get_limited_results

        Retrieves the limited results of the provided SPARQL query  # noqa: E501
        """
        pass

    def test_post_rdf_query(self):
        """Test case for post_rdf_query

        Retrieves the results of the provided SPARQL query  # noqa: E501
        """
        pass

    def test_post_rdf_query_limited(self):
        """Test case for post_rdf_query_limited

        Retrieves the results of the provided SPARQL query  # noqa: E501
        """
        pass

    def test_rdf_query(self):
        """Test case for rdf_query

        Retrieves the results of the provided SPARQL query  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
