# coding: utf-8

"""
    Mobi

    Mobi REST API Documentation  # noqa: E501

    OpenAPI spec version: 1.22.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.commits_api import CommitsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCommitsApi(unittest.TestCase):
    """CommitsApi unit test stubs"""

    def setUp(self):
        self.api = CommitsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_commit(self):
        """Test case for get_commit

        Retrieves the Commit specified by the provided ID  # noqa: E501
        """
        pass

    def test_get_commit_history(self):
        """Test case for get_commit_history

        Retrieves the Commit history specified by the provided ID  # noqa: E501
        """
        pass

    def test_get_compiled_resource1(self):
        """Test case for get_compiled_resource1

        Retrieves the Commit specified by the provided ID  # noqa: E501
        """
        pass

    def test_get_difference1(self):
        """Test case for get_difference1

        Gets the Difference for the specified commit or between the two specified Commits. If a limit and offset are passed in, retrieve the differences for the paged subjects using the limit and offset. If the offset is greater than the number of subjects, the additions and deletions arrays of the response object will be empty arrays. If limit and offset are provided, a header called has-more-results will be added to the response object that indicates whether more pages of results exist.  # noqa: E501
        """
        pass

    def test_get_difference_for_subject(self):
        """Test case for get_difference_for_subject

        Retrieves the Difference in the specified commit for the specified subject  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
