# coding: utf-8

"""
    Mobi

    Mobi REST API Documentation  # noqa: E501

    OpenAPI spec version: 1.22.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.encoded_query import EncodedQuery  # noqa: E501
from swagger_client.rest import ApiException


class TestEncodedQuery(unittest.TestCase):
    """EncodedQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEncodedQuery(self):
        """Test EncodedQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.encoded_query.EncodedQuery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
