# coding: utf-8

"""
    Mobi

    Mobi REST API Documentation  # noqa: E501

    OpenAPI spec version: 1.22.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.groups_api import GroupsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self):
        self.api = GroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_group_roles(self):
        """Test case for add_group_roles

        Add roles to a Mobi Group  # noqa: E501
        """
        pass

    def test_add_group_user(self):
        """Test case for add_group_user

        Add a Mobi User to a Group  # noqa: E501
        """
        pass

    def test_create_group(self):
        """Test case for create_group

        Create a new Mobi Group  # noqa: E501
        """
        pass

    def test_delete_group(self):
        """Test case for delete_group

        Remove a Mobi Group  # noqa: E501
        """
        pass

    def test_get_group(self):
        """Test case for get_group

        Get a single Mobi Group  # noqa: E501
        """
        pass

    def test_get_group_roles(self):
        """Test case for get_group_roles

        List roles of a Mobi Group  # noqa: E501
        """
        pass

    def test_get_group_users(self):
        """Test case for get_group_users

        List users of a Mobi Group  # noqa: E501
        """
        pass

    def test_get_groups(self):
        """Test case for get_groups

        Get all Mobi Groups  # noqa: E501
        """
        pass

    def test_remove_group_role(self):
        """Test case for remove_group_role

        Remove role from a Mobi Group  # noqa: E501
        """
        pass

    def test_remove_group_user(self):
        """Test case for remove_group_user

        Remove a Mobi User from a Group  # noqa: E501
        """
        pass

    def test_update_group(self):
        """Test case for update_group

        Update a Mobi Group's information  # noqa: E501
        """
        pass

    def test_verify_url(self):
        """Test case for verify_url

        Checks to see if the provided URL is resolvable  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
