# coding: utf-8

"""
    Mobi

    Mobi REST API Documentation  # noqa: E501

    OpenAPI spec version: 1.22.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CatalogIdRecordsBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'title': 'str',
        'identifier': 'str',
        'description': 'str',
        'markdown': 'str',
        'keywords': 'list[str]'
    }

    attribute_map = {
        'type': 'type',
        'title': 'title',
        'identifier': 'identifier',
        'description': 'description',
        'markdown': 'markdown',
        'keywords': 'keywords'
    }

    def __init__(self, type=None, title=None, identifier=None, description=None, markdown=None, keywords=None):  # noqa: E501
        """CatalogIdRecordsBody - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._title = None
        self._identifier = None
        self._description = None
        self._markdown = None
        self._keywords = None
        self.discriminator = None
        if type is not None:
            self.type = type
        if title is not None:
            self.title = title
        if identifier is not None:
            self.identifier = identifier
        if description is not None:
            self.description = description
        if markdown is not None:
            self.markdown = markdown
        if keywords is not None:
            self.keywords = keywords

    @property
    def type(self):
        """Gets the type of this CatalogIdRecordsBody.  # noqa: E501

        Required IRI of the type for the new RecordMust be a valid IRI for a Record or one of its subclasses  # noqa: E501

        :return: The type of this CatalogIdRecordsBody.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this CatalogIdRecordsBody.

        Required IRI of the type for the new RecordMust be a valid IRI for a Record or one of its subclasses  # noqa: E501

        :param type: The type of this CatalogIdRecordsBody.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def title(self):
        """Gets the title of this CatalogIdRecordsBody.  # noqa: E501

        Required title for the new Record  # noqa: E501

        :return: The title of this CatalogIdRecordsBody.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this CatalogIdRecordsBody.

        Required title for the new Record  # noqa: E501

        :param title: The title of this CatalogIdRecordsBody.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def identifier(self):
        """Gets the identifier of this CatalogIdRecordsBody.  # noqa: E501

        Required identifier for the new Record. Must be a valid IRI  # noqa: E501

        :return: The identifier of this CatalogIdRecordsBody.  # noqa: E501
        :rtype: str
        """
        return self._identifier

    @identifier.setter
    def identifier(self, identifier):
        """Sets the identifier of this CatalogIdRecordsBody.

        Required identifier for the new Record. Must be a valid IRI  # noqa: E501

        :param identifier: The identifier of this CatalogIdRecordsBody.  # noqa: E501
        :type: str
        """

        self._identifier = identifier

    @property
    def description(self):
        """Gets the description of this CatalogIdRecordsBody.  # noqa: E501

        Optional description for the new Record  # noqa: E501

        :return: The description of this CatalogIdRecordsBody.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CatalogIdRecordsBody.

        Optional description for the new Record  # noqa: E501

        :param description: The description of this CatalogIdRecordsBody.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def markdown(self):
        """Gets the markdown of this CatalogIdRecordsBody.  # noqa: E501

        Optional markdown abstract for the new Record  # noqa: E501

        :return: The markdown of this CatalogIdRecordsBody.  # noqa: E501
        :rtype: str
        """
        return self._markdown

    @markdown.setter
    def markdown(self, markdown):
        """Sets the markdown of this CatalogIdRecordsBody.

        Optional markdown abstract for the new Record  # noqa: E501

        :param markdown: The markdown of this CatalogIdRecordsBody.  # noqa: E501
        :type: str
        """

        self._markdown = markdown

    @property
    def keywords(self):
        """Gets the keywords of this CatalogIdRecordsBody.  # noqa: E501

        Optional list of keywords strings for the new Record  # noqa: E501

        :return: The keywords of this CatalogIdRecordsBody.  # noqa: E501
        :rtype: list[str]
        """
        return self._keywords

    @keywords.setter
    def keywords(self, keywords):
        """Sets the keywords of this CatalogIdRecordsBody.

        Optional list of keywords strings for the new Record  # noqa: E501

        :param keywords: The keywords of this CatalogIdRecordsBody.  # noqa: E501
        :type: list[str]
        """

        self._keywords = keywords

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CatalogIdRecordsBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CatalogIdRecordsBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
