# coding: utf-8

"""
    Mobi

    Mobi REST API Documentation  # noqa: E501

    OpenAPI spec version: 1.22.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DelimitedfilesDocumentNameBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'delimited_file': 'str'
    }

    attribute_map = {
        'delimited_file': 'delimitedFile'
    }

    def __init__(self, delimited_file=None):  # noqa: E501
        """DelimitedfilesDocumentNameBody - a model defined in Swagger"""  # noqa: E501
        self._delimited_file = None
        self.discriminator = None
        if delimited_file is not None:
            self.delimited_file = delimited_file

    @property
    def delimited_file(self):
        """Gets the delimited_file of this DelimitedfilesDocumentNameBody.  # noqa: E501

        InputStream of a delimited document passed as form data  # noqa: E501

        :return: The delimited_file of this DelimitedfilesDocumentNameBody.  # noqa: E501
        :rtype: str
        """
        return self._delimited_file

    @delimited_file.setter
    def delimited_file(self, delimited_file):
        """Sets the delimited_file of this DelimitedfilesDocumentNameBody.

        InputStream of a delimited document passed as form data  # noqa: E501

        :param delimited_file: The delimited_file of this DelimitedfilesDocumentNameBody.  # noqa: E501
        :type: str
        """

        self._delimited_file = delimited_file

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DelimitedfilesDocumentNameBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DelimitedfilesDocumentNameBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
