# coding: utf-8

"""
    Mobi

    Mobi REST API Documentation  # noqa: E501

    OpenAPI spec version: 1.22.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DocumentNameMappreviewBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'jsonld': 'str'
    }

    attribute_map = {
        'jsonld': 'jsonld'
    }

    def __init__(self, jsonld=None):  # noqa: E501
        """DocumentNameMappreviewBody - a model defined in Swagger"""  # noqa: E501
        self._jsonld = None
        self.discriminator = None
        if jsonld is not None:
            self.jsonld = jsonld

    @property
    def jsonld(self):
        """Gets the jsonld of this DocumentNameMappreviewBody.  # noqa: E501

        Mapping in JSON-LD  # noqa: E501

        :return: The jsonld of this DocumentNameMappreviewBody.  # noqa: E501
        :rtype: str
        """
        return self._jsonld

    @jsonld.setter
    def jsonld(self, jsonld):
        """Sets the jsonld of this DocumentNameMappreviewBody.

        Mapping in JSON-LD  # noqa: E501

        :param jsonld: The jsonld of this DocumentNameMappreviewBody.  # noqa: E501
        :type: str
        """

        self._jsonld = jsonld

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DocumentNameMappreviewBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DocumentNameMappreviewBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
