# coding: utf-8

"""
    Mobi

    Mobi REST API Documentation  # noqa: E501

    OpenAPI spec version: 1.22.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MappingsBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'title': 'str',
        'description': 'str',
        'markdown': 'str',
        'keywords': 'list[str]',
        'file': 'str',
        'jsonld': 'str'
    }

    attribute_map = {
        'title': 'title',
        'description': 'description',
        'markdown': 'markdown',
        'keywords': 'keywords',
        'file': 'file',
        'jsonld': 'jsonld'
    }

    def __init__(self, title=None, description=None, markdown=None, keywords=None, file=None, jsonld=None):  # noqa: E501
        """MappingsBody - a model defined in Swagger"""  # noqa: E501
        self._title = None
        self._description = None
        self._markdown = None
        self._keywords = None
        self._file = None
        self._jsonld = None
        self.discriminator = None
        if title is not None:
            self.title = title
        if description is not None:
            self.description = description
        if markdown is not None:
            self.markdown = markdown
        if keywords is not None:
            self.keywords = keywords
        if file is not None:
            self.file = file
        if jsonld is not None:
            self.jsonld = jsonld

    @property
    def title(self):
        """Gets the title of this MappingsBody.  # noqa: E501

        Required title for the new MappingRecord  # noqa: E501

        :return: The title of this MappingsBody.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this MappingsBody.

        Required title for the new MappingRecord  # noqa: E501

        :param title: The title of this MappingsBody.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def description(self):
        """Gets the description of this MappingsBody.  # noqa: E501

        Optional description for the new MappingRecord  # noqa: E501

        :return: The description of this MappingsBody.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this MappingsBody.

        Optional description for the new MappingRecord  # noqa: E501

        :param description: The description of this MappingsBody.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def markdown(self):
        """Gets the markdown of this MappingsBody.  # noqa: E501

        Optional markdown abstract for the new MappingRecord  # noqa: E501

        :return: The markdown of this MappingsBody.  # noqa: E501
        :rtype: str
        """
        return self._markdown

    @markdown.setter
    def markdown(self, markdown):
        """Sets the markdown of this MappingsBody.

        Optional markdown abstract for the new MappingRecord  # noqa: E501

        :param markdown: The markdown of this MappingsBody.  # noqa: E501
        :type: str
        """

        self._markdown = markdown

    @property
    def keywords(self):
        """Gets the keywords of this MappingsBody.  # noqa: E501

        Optional list of keywords strings for the new MappingRecord  # noqa: E501

        :return: The keywords of this MappingsBody.  # noqa: E501
        :rtype: list[str]
        """
        return self._keywords

    @keywords.setter
    def keywords(self, keywords):
        """Sets the keywords of this MappingsBody.

        Optional list of keywords strings for the new MappingRecord  # noqa: E501

        :param keywords: The keywords of this MappingsBody.  # noqa: E501
        :type: list[str]
        """

        self._keywords = keywords

    @property
    def file(self):
        """Gets the file of this MappingsBody.  # noqa: E501

        InputStream of a mapping file passed as form data  # noqa: E501

        :return: The file of this MappingsBody.  # noqa: E501
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this MappingsBody.

        InputStream of a mapping file passed as form data  # noqa: E501

        :param file: The file of this MappingsBody.  # noqa: E501
        :type: str
        """

        self._file = file

    @property
    def jsonld(self):
        """Gets the jsonld of this MappingsBody.  # noqa: E501

        Mapping serialized as JSON-LD  # noqa: E501

        :return: The jsonld of this MappingsBody.  # noqa: E501
        :rtype: str
        """
        return self._jsonld

    @jsonld.setter
    def jsonld(self, jsonld):
        """Sets the jsonld of this MappingsBody.

        Mapping serialized as JSON-LD  # noqa: E501

        :param jsonld: The jsonld of this MappingsBody.  # noqa: E501
        :type: str
        """

        self._jsonld = jsonld

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MappingsBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MappingsBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
