# coding: utf-8

"""
    Mobi

    Mobi REST API Documentation  # noqa: E501

    OpenAPI spec version: 1.22.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RecordIdInprogresscommitBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'additions': 'str',
        'deletions': 'str'
    }

    attribute_map = {
        'additions': 'additions',
        'deletions': 'deletions'
    }

    def __init__(self, additions=None, deletions=None):  # noqa: E501
        """RecordIdInprogresscommitBody - a model defined in Swagger"""  # noqa: E501
        self._additions = None
        self._deletions = None
        self.discriminator = None
        if additions is not None:
            self.additions = additions
        if deletions is not None:
            self.deletions = deletions

    @property
    def additions(self):
        """Gets the additions of this RecordIdInprogresscommitBody.  # noqa: E501

        String of JSON-LD that corresponds to the statements that were added to the entity  # noqa: E501

        :return: The additions of this RecordIdInprogresscommitBody.  # noqa: E501
        :rtype: str
        """
        return self._additions

    @additions.setter
    def additions(self, additions):
        """Sets the additions of this RecordIdInprogresscommitBody.

        String of JSON-LD that corresponds to the statements that were added to the entity  # noqa: E501

        :param additions: The additions of this RecordIdInprogresscommitBody.  # noqa: E501
        :type: str
        """

        self._additions = additions

    @property
    def deletions(self):
        """Gets the deletions of this RecordIdInprogresscommitBody.  # noqa: E501

        String of JSON-LD that corresponds to the statements that were deleted in the entity  # noqa: E501

        :return: The deletions of this RecordIdInprogresscommitBody.  # noqa: E501
        :rtype: str
        """
        return self._deletions

    @deletions.setter
    def deletions(self, deletions):
        """Sets the deletions of this RecordIdInprogresscommitBody.

        String of JSON-LD that corresponds to the statements that were deleted in the entity  # noqa: E501

        :param deletions: The deletions of this RecordIdInprogresscommitBody.  # noqa: E501
        :type: str
        """

        self._deletions = deletions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RecordIdInprogresscommitBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RecordIdInprogresscommitBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
