# coding: utf-8

"""
    Mobi

    Mobi REST API Documentation  # noqa: E501

    OpenAPI spec version: 1.22.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RecordIdTagsBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'title': 'str',
        'description': 'str',
        'iri': 'str',
        'commit': 'str'
    }

    attribute_map = {
        'title': 'title',
        'description': 'description',
        'iri': 'iri',
        'commit': 'commit'
    }

    def __init__(self, title=None, description=None, iri=None, commit=None):  # noqa: E501
        """RecordIdTagsBody - a model defined in Swagger"""  # noqa: E501
        self._title = None
        self._description = None
        self._iri = None
        self._commit = None
        self.discriminator = None
        if title is not None:
            self.title = title
        if description is not None:
            self.description = description
        if iri is not None:
            self.iri = iri
        if commit is not None:
            self.commit = commit

    @property
    def title(self):
        """Gets the title of this RecordIdTagsBody.  # noqa: E501

        Required title for the new Tag  # noqa: E501

        :return: The title of this RecordIdTagsBody.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this RecordIdTagsBody.

        Required title for the new Tag  # noqa: E501

        :param title: The title of this RecordIdTagsBody.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def description(self):
        """Gets the description of this RecordIdTagsBody.  # noqa: E501

        Optional description for the new Tag  # noqa: E501

        :return: The description of this RecordIdTagsBody.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this RecordIdTagsBody.

        Optional description for the new Tag  # noqa: E501

        :param description: The description of this RecordIdTagsBody.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def iri(self):
        """Gets the iri of this RecordIdTagsBody.  # noqa: E501

        Required IRI for the new Tag. Must be unique in the repository  # noqa: E501

        :return: The iri of this RecordIdTagsBody.  # noqa: E501
        :rtype: str
        """
        return self._iri

    @iri.setter
    def iri(self, iri):
        """Sets the iri of this RecordIdTagsBody.

        Required IRI for the new Tag. Must be unique in the repository  # noqa: E501

        :param iri: The iri of this RecordIdTagsBody.  # noqa: E501
        :type: str
        """

        self._iri = iri

    @property
    def commit(self):
        """Gets the commit of this RecordIdTagsBody.  # noqa: E501

        Required String representing the Commit ID  # noqa: E501

        :return: The commit of this RecordIdTagsBody.  # noqa: E501
        :rtype: str
        """
        return self._commit

    @commit.setter
    def commit(self, commit):
        """Sets the commit of this RecordIdTagsBody.

        Required String representing the Commit ID  # noqa: E501

        :param commit: The commit of this RecordIdTagsBody.  # noqa: E501
        :type: str
        """

        self._commit = commit

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RecordIdTagsBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RecordIdTagsBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
